[package]
name = "nalgebra_block_triangularization"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["lib"]

[dependencies]
nalgebra = "0.34"

[dev-dependencies]
proptest = "1.9.0"
pretty_assertions = "1.4.1"
test-case = "3.3.1"
